version: '3.7'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
